services:

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./.env


volumes:
  postgres_data:
  static_volume: